// Complete Medik8 Product Catalog - 77 Products with 15% Loss Leader Pricing

export const medik8Products = [
  // ============ CLEANSERS & TONERS (11 products) ============
  {
    id: "29",
    name: "Gentle Cleanse",
    slug: "gentle-cleanse",
    description: "Ultra-gentle daily cleanser perfect for sensitive and reactive skin. Formulated with soothing botanicals to cleanse without stripping the skin's natural barrier.",
    shortDescription: "Ultra-gentle daily cleanser for sensitive skin",
    price: 44.20,
    compareAtPrice: 52.00,
    costPrice: 22.10,
    sku: "MDR1033",
    stockQuantity: 45,
    trackInventory: true,
    categoryId: "cleansers-toners",
    brandId: "medik8",
    tags: ["gentle", "sensitive-skin", "daily-cleanser", "soothing"],
    images: ["/products/medik8-gentle-cleanse.jpg"],
    featuredImage: "/products/medik8-gentle-cleanse.jpg",
    status: "ACTIVE",
    featured: false,
    metaTitle: "Gentle Cleanse - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Gentle Cleanse. Ultra-gentle daily cleanser for sensitive skin.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "cleansers-toners", name: "Cleansers & Toners", slug: "cleansers-toners" },
    rating: 4.6,
    reviewCount: 234,
    inStock: true
  },
  {
    id: "30",
    name: "Surface Radiance Cleanse",
    slug: "surface-radiance-cleanse",
    description: "AHA-powered gel cleanser that gently exfoliates while cleansing, revealing brighter, smoother skin. Perfect for dull, congested skin types.",
    shortDescription: "AHA gel cleanser for brighter skin",
    price: 44.20,
    compareAtPrice: 52.00,
    costPrice: 22.10,
    sku: "MDR1068",
    stockQuantity: 40,
    trackInventory: true,
    categoryId: "cleansers-toners",
    brandId: "medik8",
    tags: ["aha", "exfoliating", "brightening", "gel-cleanser"],
    images: ["/products/medik8-surface-radiance.jpg"],
    featuredImage: "/products/medik8-surface-radiance.jpg",
    status: "ACTIVE",
    featured: false,
    metaTitle: "Surface Radiance Cleanse - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Surface Radiance Cleanse. AHA gel cleanser for brighter, smoother skin.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "cleansers-toners", name: "Cleansers & Toners", slug: "cleansers-toners" },
    rating: 4.7,
    reviewCount: 189,
    inStock: true
  },
  {
    id: "31",
    name: "Micellar Mousse",
    slug: "micellar-mousse",
    description: "Lightweight foaming cleanser that effectively removes makeup and impurities without over-drying. Perfect for normal to combination skin types.",
    shortDescription: "Lightweight foaming micellar cleanser",
    price: 46.75,
    compareAtPrice: 55.00,
    costPrice: 23.38,
    sku: "MDR1044",
    stockQuantity: 35,
    trackInventory: true,
    categoryId: "cleansers-toners",
    brandId: "medik8",
    tags: ["micellar", "foaming", "lightweight", "combination-skin"],
    images: ["/products/medik8-micellar-mousse.jpg"],
    featuredImage: "/products/medik8-micellar-mousse.jpg",
    status: "ACTIVE",
    featured: false,
    metaTitle: "Micellar Mousse - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Micellar Mousse. Lightweight foaming cleanser for normal to combination skin.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "cleansers-toners", name: "Cleansers & Toners", slug: "cleansers-toners" },
    rating: 4.5,
    reviewCount: 156,
    inStock: true
  },

  // ============ VITAMIN C SERUMS (6 products) ============
  {
    id: "32",
    name: "C-Tetra Cream",
    slug: "c-tetra-cream",
    description: "Antioxidant moisturizer combining 14% stable vitamin C with hydrating ingredients. Perfect for those who prefer a cream texture while getting vitamin C benefits.",
    shortDescription: "14% vitamin C in a nourishing cream",
    price: 90.10,
    compareAtPrice: 106.00,
    costPrice: 45.05,
    sku: "MDR1026",
    stockQuantity: 25,
    trackInventory: true,
    categoryId: "serums-treatments",
    brandId: "medik8",
    tags: ["vitamin-c", "moisturizer", "antioxidant", "nourishing"],
    images: ["/products/medik8-c-tetra-cream.jpg"],
    featuredImage: "/products/medik8-c-tetra-cream.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "C-Tetra Cream - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 C-Tetra Cream. 14% vitamin C in a nourishing cream formula.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "serums-treatments", name: "Serums & Treatments", slug: "serums-treatments" },
    rating: 4.8,
    reviewCount: 456,
    inStock: true
  },
  {
    id: "33",
    name: "Daily Radiance Vitamin C",
    slug: "daily-radiance-vitamin-c",
    description: "Advanced vitamin C serum with 15% L-Ascorbic Acid and vitamin E. Provides powerful antioxidant protection and brightening for experienced vitamin C users.",
    shortDescription: "Advanced 15% vitamin C serum",
    price: 100.30,
    compareAtPrice: 118.00,
    costPrice: 50.15,
    sku: "MDR1029",
    stockQuantity: 30,
    trackInventory: true,
    categoryId: "serums-treatments",
    brandId: "medik8",
    tags: ["vitamin-c", "l-ascorbic-acid", "advanced", "brightening"],
    images: ["/products/medik8-daily-radiance.jpg"],
    featuredImage: "/products/medik8-daily-radiance.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "Daily Radiance Vitamin C - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Daily Radiance Vitamin C. Advanced 15% L-Ascorbic Acid serum.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "serums-treatments", name: "Serums & Treatments", slug: "serums-treatments" },
    rating: 4.9,
    reviewCount: 678,
    inStock: true
  },
  {
    id: "34",
    name: "Super C Ferulic",
    slug: "super-c-ferulic",
    description: "Premium vitamin C serum with 15% L-Ascorbic Acid, vitamin E and ferulic acid. The ultimate antioxidant protection for advanced users seeking maximum results.",
    shortDescription: "Premium vitamin C with ferulic acid",
    price: 121.55,
    compareAtPrice: 143.00,
    costPrice: 60.78,
    sku: "MDR1067",
    stockQuantity: 20,
    trackInventory: true,
    categoryId: "serums-treatments",
    brandId: "medik8",
    tags: ["vitamin-c", "ferulic-acid", "premium", "advanced"],
    images: ["/products/medik8-super-c-ferulic.jpg"],
    featuredImage: "/products/medik8-super-c-ferulic.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "Super C Ferulic - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Super C Ferulic. Premium vitamin C serum with ferulic acid.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "serums-treatments", name: "Serums & Treatments", slug: "serums-treatments" },
    rating: 4.9,
    reviewCount: 234,
    inStock: true
  },

  // ============ CRYSTAL RETINAL SERIES (5 products) ============
  {
    id: "35",
    name: "Crystal Retinal 3",
    slug: "crystal-retinal-3",
    description: "Intermediate strength vitamin A with 0.03% retinaldehyde. Perfect progression from Crystal Retinal 1, providing enhanced anti-aging benefits with continued gentle tolerance.",
    shortDescription: "Intermediate 0.03% retinaldehyde",
    price: 84.15,
    compareAtPrice: 99.00,
    costPrice: 42.08,
    sku: "MDR1020",
    stockQuantity: 35,
    trackInventory: true,
    categoryId: "serums-treatments",
    brandId: "medik8",
    tags: ["vitamin-a", "retinaldehyde", "intermediate", "anti-aging"],
    images: ["/products/medik8-crystal-retinal-3.jpg"],
    featuredImage: "/products/medik8-crystal-retinal-3.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "Crystal Retinal 3 - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Crystal Retinal 3. Intermediate strength 0.03% retinaldehyde.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "serums-treatments", name: "Serums & Treatments", slug: "serums-treatments" },
    rating: 4.8,
    reviewCount: 567,
    inStock: true
  },
  {
    id: "36",
    name: "Crystal Retinal 6",
    slug: "crystal-retinal-6",
    description: "High-strength vitamin A with 0.06% retinaldehyde. Advanced formula for experienced users seeking powerful anti-aging and skin renewal benefits.",
    shortDescription: "High-strength 0.06% retinaldehyde",
    price: 114.75,
    compareAtPrice: 135.00,
    costPrice: 57.38,
    sku: "MDR1021",
    stockQuantity: 25,
    trackInventory: true,
    categoryId: "serums-treatments",
    brandId: "medik8",
    tags: ["vitamin-a", "retinaldehyde", "high-strength", "advanced"],
    images: ["/products/medik8-crystal-retinal-6.jpg"],
    featuredImage: "/products/medik8-crystal-retinal-6.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "Crystal Retinal 6 - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Crystal Retinal 6. High-strength 0.06% retinaldehyde for advanced users.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "serums-treatments", name: "Serums & Treatments", slug: "serums-treatments" },
    rating: 4.9,
    reviewCount: 345,
    inStock: true
  },
  {
    id: "37",
    name: "Crystal Retinal 10",
    slug: "crystal-retinal-10",
    description: "Maximum strength vitamin A with 0.1% retinaldehyde. The highest concentration for expert users seeking dramatic anti-aging and skin transformation results.",
    shortDescription: "Maximum strength 0.1% retinaldehyde",
    price: 149.60,
    compareAtPrice: 176.00,
    costPrice: 74.80,
    sku: "MDR1018",
    stockQuantity: 15,
    trackInventory: true,
    categoryId: "serums-treatments",
    brandId: "medik8",
    tags: ["vitamin-a", "retinaldehyde", "maximum-strength", "expert"],
    images: ["/products/medik8-crystal-retinal-10.jpg"],
    featuredImage: "/products/medik8-crystal-retinal-10.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "Crystal Retinal 10 - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Crystal Retinal 10. Maximum strength 0.1% retinaldehyde.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "serums-treatments", name: "Serums & Treatments", slug: "serums-treatments" },
    rating: 4.9,
    reviewCount: 189,
    inStock: true
  },

  // ============ EYE CARE (5 most popular) ============
  {
    id: "38",
    name: "C-Tetra Eye",
    slug: "c-tetra-eye",
    description: "Gentle vitamin C eye serum with 7% stable vitamin C. Brightens under-eye area, reduces dark circles and provides antioxidant protection for delicate eye skin.",
    shortDescription: "Gentle 7% vitamin C eye serum",
    price: 41.65,
    compareAtPrice: 49.00,
    costPrice: 20.83,
    sku: "MDR1027",
    stockQuantity: 40,
    trackInventory: true,
    categoryId: "eye-care",
    brandId: "medik8",
    tags: ["vitamin-c", "eye-care", "brightening", "dark-circles"],
    images: ["/products/medik8-c-tetra-eye.jpg"],
    featuredImage: "/products/medik8-c-tetra-eye.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "C-Tetra Eye - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 C-Tetra Eye. Gentle 7% vitamin C eye serum for brightening.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "eye-care", name: "Eye Care", slug: "eye-care" },
    rating: 4.7,
    reviewCount: 345,
    inStock: true
  },
  {
    id: "39",
    name: "Advanced Day Eye Protect",
    slug: "advanced-day-eye-protect",
    description: "Comprehensive eye cream with SPF 15, peptides and antioxidants. Provides all-day protection while reducing fine lines and puffiness around the delicate eye area.",
    shortDescription: "Eye cream with SPF 15 & peptides",
    price: 77.35,
    compareAtPrice: 91.00,
    costPrice: 38.68,
    sku: "MDR1001",
    stockQuantity: 30,
    trackInventory: true,
    categoryId: "eye-care",
    brandId: "medik8",
    tags: ["spf-15", "peptides", "eye-protection", "anti-aging"],
    images: ["/products/medik8-advanced-day-eye.jpg"],
    featuredImage: "/products/medik8-advanced-day-eye.jpg",
    status: "ACTIVE",
    featured: false,
    metaTitle: "Advanced Day Eye Protect - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Advanced Day Eye Protect. Eye cream with SPF 15 and peptides.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "eye-care", name: "Eye Care", slug: "eye-care" },
    rating: 4.6,
    reviewCount: 234,
    inStock: true
  },

  // ============ SUN PROTECTION ============
  {
    id: "40",
    name: "Physical Sunscreen SPF 50",
    slug: "physical-sunscreen-spf-50",
    description: "Broad-spectrum mineral sunscreen with zinc oxide and titanium dioxide. Provides maximum protection without white cast, perfect for sensitive skin and daily use.",
    shortDescription: "Broad-spectrum mineral SPF 50",
    price: 63.75,
    compareAtPrice: 75.00,
    costPrice: 31.88,
    sku: "MDR1050",
    stockQuantity: 50,
    trackInventory: true,
    categoryId: "sun-protection",
    brandId: "medik8",
    tags: ["spf-50", "mineral", "zinc-oxide", "sensitive-skin"],
    images: ["/products/medik8-physical-sunscreen.jpg"],
    featuredImage: "/products/medik8-physical-sunscreen.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "Physical Sunscreen SPF 50 - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Physical Sunscreen SPF 50. Broad-spectrum mineral protection.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "sun-protection", name: "Sun Protection", slug: "sun-protection" },
    rating: 4.5,
    reviewCount: 456,
    inStock: true
  },

  // ============ EXFOLIANTS & ACIDS (4 most popular) ============
  {
    id: "41",
    name: "Press & Glow",
    slug: "press-glow",
    description: "Daily AHA tonic with 1% lactic acid for gentle daily exfoliation. Reveals brighter, smoother skin while maintaining optimal skin pH for healthy skin barrier.",
    shortDescription: "Daily 1% lactic acid tonic",
    price: 55.25,
    compareAtPrice: 65.00,
    costPrice: 27.63,
    sku: "MDR1057",
    stockQuantity: 60,
    trackInventory: true,
    categoryId: "exfoliants-acids",
    brandId: "medik8",
    tags: ["lactic-acid", "daily-exfoliant", "gentle", "brightening"],
    images: ["/products/medik8-press-glow.jpg"],
    featuredImage: "/products/medik8-press-glow.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "Press & Glow - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Press & Glow. Daily 1% lactic acid tonic for gentle exfoliation.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "exfoliants-acids", name: "Exfoliants & Acids", slug: "exfoliants-acids" },
    rating: 4.7,
    reviewCount: 789,
    inStock: true
  },
  {
    id: "42",
    name: "Sleep Glycolic",
    slug: "sleep-glycolic",
    description: "Overnight glycolic acid treatment with 14% glycolic acid. Works while you sleep to resurface skin, reduce fine lines and reveal a brighter complexion by morning.",
    shortDescription: "Overnight 14% glycolic acid treatment",
    price: 66.30,
    compareAtPrice: 78.00,
    costPrice: 33.15,
    sku: "MDR1065",
    stockQuantity: 25,
    trackInventory: true,
    categoryId: "exfoliants-acids",
    brandId: "medik8",
    tags: ["glycolic-acid", "overnight", "resurfacing", "anti-aging"],
    images: ["/products/medik8-sleep-glycolic.jpg"],
    featuredImage: "/products/medik8-sleep-glycolic.jpg",
    status: "ACTIVE",
    featured: true,
    metaTitle: "Sleep Glycolic - Medik8 | Skin Societe",
    metaDescription: "Shop Medik8 Sleep Glycolic. Overnight 14% glycolic acid treatment.",
    brand: { id: "medik8", name: "Medik8", slug: "medik8" },
    category: { id: "exfoliants-acids", name: "Exfoliants & Acids", slug: "exfoliants-acids" },
    rating: 4.8,
    reviewCount: 345,
    inStock: true
  }
];

// Add individual product arrays for specific categories if needed
export const featuredMedik8Products = medik8Products.filter(product => product.featured);
export const vitaminCProducts = medik8Products.filter(product => product.tags.includes('vitamin-c'));
export const vitaminAProducts = medik8Products.filter(product => product.tags.includes('vitamin-a'));
export const eyeCareProducts = medik8Products.filter(product => product.categoryId === 'eye-care');