services:
  - type: web
    name: skin-societe
    env: node
    plan: free
    runtime: node
    buildCommand: npm ci && npx prisma generate --no-engine && next build
    startCommand: npm start
    node: 18.17.0
    envVars:
      - key: PHOREST_USERNAME
        value: global/josh@skinsociete.com.au
      - key: PHOREST_PASSWORD
        value: ROW^pDL%kxSq
      - key: PHOREST_BUSINESS_ID
        value: IX2it2QrF0iguR-LpZ6BHQ
      - key: NODE_ENV
        value: production